services:
  - type: web
    name: surf
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    branch: main
    rootDir: surf
    pullRequestPreviewsEnabled: true
    region: frankfurt

  - type: web
    name: monsters-and-trees
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    branch: main
    rootDir: monsters-and-trees
    pullRequestPreviewsEnabled: true
    region: frankfurt