services:
  - type: web
    name: surf
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    branch: main
    rootDir: surf
    pullRequestPreviewsEnabled: true
    region: frankfurt

  - type: web
    name: monsters-and-trees
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    branch: main
    rootDir: monsters-and-trees
    pullRequestPreviewsEnabled: true
    region: frankfurt

  - type: web
    name: simple-chat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    branch: main
    rootDir: simple-chat
    pullRequestPreviewsEnabled: true
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: contacts-and-cal-server
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    plan: free
    branch: main
    rootDir: contacts-and-cal
    pullRequestPreviewsEnabled: true
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    databaseName: db
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all (public). Change to specific IP/CIDR or remove for internal-only access.
    region: frankfurt